### ISSUE TITLE
We need a nice logo

### ISSUE THREAD

**Issue by amogorkon** [amogorkon/justuse#348]

**Comment by oneamanish** [comment]
see my pull req.

**Comment by rustyxlol** [comment]
Something like a finger snap might convey the gist of Just use.

I yoinked the cube from @amogorkon's logo, which conveys that it's related to packages 📦, maybe they should be a bit fatter? 

<a href="url"><img src="https://user-images.githubusercontent.com/27452933/164595997-460bf983-97ef-414f-a388-7855e29a3a35.png" height="256" ></a>


Something else that I thought of was a weight scale but it didn't look that good. Made this instead

<a href="url"><img src="https://user-images.githubusercontent.com/27452933/164595707-2f5a98b7-a515-4bee-b49b-af3d5f77db07.png" height="128" ></a>


Perhaps a magic wand would look better since Just use is.. magical? :D

**Comment by amogorkon** [comment]
Oh, cool, very nice ideas 👍 I like the finger snapping, but it's a bit bulky (similar to my original idea) - maybe combine the magic wand with the fingersnap-box for additional awesomeness but more compact?

**Comment by amogorkon** [comment]
![logo](https://user-images.githubusercontent.com/16521496/232826934-f08539db-be6c-44b7-805b-6239a6320302.svg)
